Paradiseapp/urls.py
from django.urls import path, include

from . import views  # Import your views
from . import api_views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'products', api_views.ProductViewSet)
router.register(r'pets', api_views.PetViewSet)
router.register(r'categories', api_views.CategoryViewSet)

urlpatterns = [
    # Main pages
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("shop/", views.shop, name="shop"),
    path("contact/", views.contact, name="contact"),
    path("messages/", views.messages_page, name="messages_page"),
    path("api/unread_count/", views.fetch_unread_count, name="fetch_unread_count"),
    path("book-appointment/", views.book_appointment, name="book_appointment"),
    path("login-required/", views.login_required_view, name="login_required"),
    # Product related
    path("product/<slug:slug>/", views.pro_details, name="product_details"),
    # path("filter_category/", views.category_products, name="category_products"),
    # Authentication
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("user-validate/<username>/<field>", views.user_validate, name="user_validate"),
    # Cart related
    path("cart/", views.carty, name="cart"),
    path("cart_count/", views.cart_count, name="cart_count"),
    path("addtocart/", views.add_to_cart, name="add_to_cart"),
    path("shopaddtocart/", views.shop_add_to_cart, name="shop_add_to_cart"),
    path("cart_data/", views.cart_data, name="cart_data"),
    # Payment
    path("proceed-to-pay/", views.razorpaycheck, name="proceed-to-pay"),
    path("proceed-to-paybuy/", views.proceed_to_pay_view, name="proceed_to_paybuy"),
    path(
        "place_order_petbuy/<int:pet_id>/",
        views.place_order_petbuy,
        name="place_order_petbuy",
    ),
    path("payment/callback/", views.payment_callback, name="payment_callback"),
    path("order-success/", views.order_success, name="order-success"),
    # Order related
    path("search-view/", views.search_view, name="search_view"),
    path(
        "update-cart-item/<int:item_id>/",
        views.update_cart_item,
        name="update_cart_item",
    ),
    path(
        "remove-from-cart/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart",
    ),
    path("checkout/", views.checkout, name="checkout"),
    path("checkoutpet/", views.checkoutpet, name="checkoutpet"),
    path("checkpet/", views.checkpet, name="checkpet"),
    path("check/", views.check, name="check"),
    path("checkbuy/", views.checkbuy, name="checkbuy"),
    path("checkpet/", views.checkpet, name="checkpet"),
    path("buy-now/", views.buy_now, name="buy_now"),
    path(
        "place_order_checkout/", views.place_order_checkout, name="place_order_checkout"
    ),
    path(
        "placeorder_buynow/<int:product_id>/",
        views.place_order_buynow,
        name="placeorder_buynow",
    ),
    # path("/proceed-to-pay/", views.razorpaycheck),
    path("view-orders/<str:t_no>", views.myorders, name="order_view"),
    path("orderslist/", views.order_list, name="orderslist"),
    # Pet related
    path("petbreed/", views.petbreed, name="petbreed"),
    path("petadopt/", views.petadopt, name="petadopt"),
    path("shophome/", views.shophome, name="shophome"),
    path("petshop/", views.petshop, name="petshop"),
    path("petsdetails/<int:pet_id>/", views.petsdetails, name="petsdetails"),
    # Adoption related
    path("petadoption/", views.petadoption, name="petadoption"),
    path("adoptionview/<slug:slug>/", views.adoption_view, name="adoptionview"),
    path("adoptionrequest/<slug:slug>/", views.adoptionrequest, name="adoptionrequest"),
    path(
        "adoptionrequestsend/<int:pet_id>/",
        views.adoption_request_send,
        name="adoptionrequestsend",
    ),
    #Pages
    path("ourteam/", views.ourteam, name="ourteam"),
    path("gallery/", views.gallery, name="gallery"),
    path("faq/", views.faq, name="faq"),
    path("teamdetails/", views.teamdetails, name="teamdetails"),
    path("blog/", views.blog, name="blog"),
    path("ourblog/",views.ourblog,name="ourblog"),
    path("change_password/", views.change_password, name="change_password"),
    # API endpoints
    path("api/", include(router.urls)),
]

petparadise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Paradiseapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paradiseapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import*
import datetime
from django.contrib.auth.forms import PasswordChangeForm

# class SignUpForm(UserCreationForm):
#     email = forms.EmailField(
#         max_length=254, help_text="Required. Enter a valid email address."
#     )
#     address = forms.CharField(max_length=255, help_text="Required. Enter your address.")
#     phone = forms.CharField(
#         max_length=20, help_text="Required. Enter your phone number."
#     )

#     class Meta:
#         model = User
#         fields = ("username", "email", "password1", "password2", "address", "phone")

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields["username"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your username"}
#         )
#         self.fields["email"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your email"}
#         )
#         self.fields["password1"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your password"}
#         )
#         self.fields["password2"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Confirm your password"}
#         )
#         self.fields["address"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your address"}
#         )
#         self.fields["phone"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your phone number"}
#         )

#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.email = self.cleaned_data["email"]
#         if commit:
#             user.save()
#         return user


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=100)
#     password = forms.CharField(widget=forms.PasswordInput())


#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields["username"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your username"}
#         )
#         self.fields["password"].widget.attrs.update(
#             {"class": "form-control", "placeholder": "Enter your password"}
#         )

# In forms.py


class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    address = forms.CharField(widget=forms.Textarea)
    city = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    postal_code = forms.CharField(max_length=10)
    phone = forms.CharField(max_length=15)
    email = forms.EmailField()
    ship_to_different_address = forms.BooleanField(required=False)
    order_notes = forms.CharField(widget=forms.Textarea, required=False)
    agree_terms = forms.BooleanField()
    payment_method = forms.ChoiceField(
        choices=(
            ("direct_bank_transfer", "Direct Bank Transfer"),
            ("check_payments", "Check Payments"),
            ("cash_on_delivery", "Cash on Delivery"),
        )
    )
    shipping_method = forms.ChoiceField(
        choices=(
            ("flat_rate", "Flat Rate: $5.00"),
            ("free_shipping", "Free Shipping"),
            ("local_pickup", "Local Pickup"),
        )
    )


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['name', 'pet_type', 'interest', 'date', 'time', 'phone']


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "species" in self.data:
            try:
                species_id = int(self.data.get("species"))
                self.fields["breed"].queryset = Breed.objects.filter(
                    species_id=species_id
                ).order_by("name")
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields["breed"].queryset = self.instance.species.breeds.order_by(
                "name"
            )

# shop/pets/forms.py


# class AdoptionRequestForm(forms.Form):
#     full_name = forms.CharField(label="Full Name")
#     email = forms.EmailField(label="Email",)
#     phone = forms.CharField(label="Phone",)
#     appointment_date = forms.DateField(
#         label="Appointment Date",
#         widget=forms.DateInput(attrs={"type": "date"}),
#     )
#     species = forms.ChoiceField(
#         label="Species", choices=[("Cat", "Cat"), ("Dog", "Dog")],
#     )
#     breed = forms.ChoiceField(
#         label="Breed", choices=[],
#     )  # Populate choices dynamically
#     pet_id = forms.ChoiceField(
#         label="Pet ID", choices=[],
#     )  # Populate choices dynamically
#     comment = forms.CharField(
#         label="Special Note", widget=forms.Textarea, required=False
#     )

#     # Custom validation can be added here if necessary
#     def clean_phone(self):
#         phone = self.cleaned_data.get("phone")
#         # Example validation: Check phone number length
#         if len(phone) < 10:
#             raise forms.ValidationError("Phone number must be at least 10 digits long.")
#         return phone

#     def clean_email(self):
#         email = self.cleaned_data.get("email")
#         # Example validation: Check email uniqueness or format
#         # Assuming you have a user model, adjust accordingly
#         if not "@" in email:
#             raise forms.ValidationError("Enter a valid email address.")
#         return email

#     def clean_appointment_date(self):
#         appointment_date = self.cleaned_data.get("appointment_date")
#         # Example validation: Ensure the date is not in the past
#         if appointment_date and appointment_date < datetime.date.today():
#             raise forms.ValidationError("Appointment date cannot be in the past.")
#         return appointment_date


class AdoptionRequestForm(forms.Form):
    fullname = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=15)
    appointment_date = forms.DateField()
    species = forms.ChoiceField(choices=[("Cat", "Cat"), ("Dog", "Dog")])
    breed = forms.CharField(max_length=100)
    comment = forms.CharField(widget=forms.Textarea, required=False)
    petadopt_id = forms.IntegerField(widget=forms.HiddenInput())


class CustomPasswordChangeForm(PasswordChangeForm):
    # Customize the form if needed
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Current Password"})
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "New Password"})
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm New Password"})
    )

    class Meta:
        model = User
        fields = ["old_password", "new_password1", "new_password2"]

templates/user/login.html
{% extends "home/base2.html" %}
{% load static %}
 {% block title %}Signup & LogIn{% endblock title %}
{% block content %}
<!-- breadcrumb-area -->
<section class="breadcrumb__area fix">
    <div class="container">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="breadcrumb__content">
                    <h3 class="title">Login & Signup</h3>
                    <nav class="breadcrumb">
                        <span property="itemListElement" typeof="ListItem">
                            <a href="{% url 'home' %}">Home</a>
                        </span>
                        <span class="breadcrumb-separator"><i class="flaticon-right-arrow-angle"></i></span>
                        <span property="itemListElement" typeof="ListItem">Login/Signup</span>
                    </nav>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="breadcrumb__img">
                    <img src="{% static 'assets/img/images/breadcrumb_img.png' %}" alt="img" data-aos="fade-left" data-aos-delay="800">
                </div>
            </div>
        </div>
    </div>
    <div class="breadcrumb__shape-wrap">
        <img src="{% static 'assets/img/images/breadcrumb_shape01.png' %}" alt="img" data-aos="fade-down-right" data-aos-delay="400">
        <img src="{% static 'assets/img/images/breadcrumb_shape02.png' %}" alt="img" data-aos="fade-up-left" data-aos-delay="400">
    </div>
</section>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} text-center" role="alert">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}

<!-- login and signup area -->
<section class="contact__area">
    <div class="container">
        <div class="row justify-content-center">
            <!-- Login Form -->
            <div class="col-lg-5">
                <div class="contact__form-wrap">
                    <form action="{% url 'login' %}" method="post" id="login-form" class="contact__form">
                        {% csrf_token %}
                        <div class="contact__form-inner">
                            <h2 class="title">
                                <span class="sub-title">Login
<strong class="shake">
                                                                  <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg" data-inject-url="{% static 'assets/img/icon/pet_icon02.svg' %}" class="injectable">
<path d="M13.4698 10.3934C14.5316 10.7921 15.7693 10.0008 16.2343 8.62072C16.6992 7.24061 16.2091 5.79916 15.1473 5.39432C14.0856 4.99562 12.8478 5.78689 12.3829 7.167C11.9243 8.55325 12.4081 9.9947 13.4698 10.3934Z" fill="currentcolor"></path>
<path d="M10.6049 5.63968C11.6981 5.79302 12.7222 4.6644 12.8855 3.11254C13.0489 1.56068 12.3012 0.17443 11.2018 0.0149505C10.1086 -0.138395 9.08446 0.99023 8.92111 2.54209C8.75148 4.10008 9.50541 5.48633 10.6049 5.63968Z" fill="currentcolor"></path>
<path d="M0.175492 8.62072C0.640418 10.0008 1.87812 10.7982 2.93991 10.3934C4.0017 9.9947 4.49176 8.54712 4.02683 7.167C3.56191 5.78689 2.3242 4.98949 1.26241 5.39432C0.200623 5.79916 -0.289433 7.24061 0.175492 8.62072Z" fill="currentcolor"></path>
<path d="M3.52421 3.11254C3.69385 4.6644 4.71794 5.79916 5.81114 5.63968C6.90434 5.48633 7.65828 4.10008 7.49492 2.54209C7.33157 0.990231 6.30748 -0.144529 5.21428 0.0149505C4.11479 0.17443 3.36086 1.56068 3.52421 3.11254Z" fill="currentcolor"></path>
<path d="M2.88337 14.8282C3.55562 16.1408 5.20799 16.7481 6.38287 16.2205C6.57764 16.1285 6.61533 16.1408 7.3567 15.7912C7.59545 15.6808 7.84676 15.601 8.20488 15.601C8.57556 15.601 8.82059 15.6808 9.05305 15.7912C9.79442 16.1408 9.82583 16.1285 10.0269 16.2205C11.2018 16.7419 12.8541 16.1347 13.5264 14.8282C14.5442 12.8408 12.4018 11.3687 11.9683 10.9516C11.0635 10.0744 10.9756 9.18503 10.8876 8.78633C10.5295 7.22834 9.26667 6.63336 8.20488 6.60269C7.14309 6.63949 5.88025 7.22834 5.52213 8.78633C5.43417 9.18503 5.34621 10.0683 4.44149 10.9516C4.00798 11.3748 1.86556 12.8408 2.88337 14.8282Z" fill="currentcolor"></path>
</svg>
                            </strong>
                                </span>
                            </h2>
                            <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" name="username" id="id_username" class="form-control" placeholder="Enter your username" required>
                                <small id="username-error" class="text-danger d-none"></small>
                            </div>
                            <div class="form-group">
                                <label for="id_password">Password</label>
                                <input type="password" name="password" id="id_password" class="form-control" placeholder="Enter your password" required>
                                <small id="password-error" class="text-danger d-none"></small>
                            </div>
                            <br>
                            <button type="submit" class="btn">Login <img src="{% static 'assets/img/icon/right_arrow.svg' %}" alt="" class="injectable"></button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Signup Form -->
            <div class="col-lg-5">
                <div class="contact__form-wrap">
                    <form action="{% url 'signup' %}" method="POST" id="signup-form" class="contact__form">
                        {% csrf_token %}
                        <div class="contact__form-inner">
                            <h2 class="title">
                                <span class="sub-title">Signup
                                    <strong class="shake">
                                                                  <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg" data-inject-url="{% static 'assets/img/icon/pet_icon02.svg' %}" class="injectable">
<path d="M13.4698 10.3934C14.5316 10.7921 15.7693 10.0008 16.2343 8.62072C16.6992 7.24061 16.2091 5.79916 15.1473 5.39432C14.0856 4.99562 12.8478 5.78689 12.3829 7.167C11.9243 8.55325 12.4081 9.9947 13.4698 10.3934Z" fill="currentcolor"></path>
<path d="M10.6049 5.63968C11.6981 5.79302 12.7222 4.6644 12.8855 3.11254C13.0489 1.56068 12.3012 0.17443 11.2018 0.0149505C10.1086 -0.138395 9.08446 0.99023 8.92111 2.54209C8.75148 4.10008 9.50541 5.48633 10.6049 5.63968Z" fill="currentcolor"></path>
<path d="M0.175492 8.62072C0.640418 10.0008 1.87812 10.7982 2.93991 10.3934C4.0017 9.9947 4.49176 8.54712 4.02683 7.167C3.56191 5.78689 2.3242 4.98949 1.26241 5.39432C0.200623 5.79916 -0.289433 7.24061 0.175492 8.62072Z" fill="currentcolor"></path>
<path d="M3.52421 3.11254C3.69385 4.6644 4.71794 5.79916 5.81114 5.63968C6.90434 5.48633 7.65828 4.10008 7.49492 2.54209C7.33157 0.990231 6.30748 -0.144529 5.21428 0.0149505C4.11479 0.17443 3.36086 1.56068 3.52421 3.11254Z" fill="currentcolor"></path>
<path d="M2.88337 14.8282C3.55562 16.1408 5.20799 16.7481 6.38287 16.2205C6.57764 16.1285 6.61533 16.1408 7.3567 15.7912C7.59545 15.6808 7.84676 15.601 8.20488 15.601C8.57556 15.601 8.82059 15.6808 9.05305 15.7912C9.79442 16.1408 9.82583 16.1285 10.0269 16.2205C11.2018 16.7419 12.8541 16.1347 13.5264 14.8282C14.5442 12.8408 12.4018 11.3687 11.9683 10.9516C11.0635 10.0744 10.9756 9.18503 10.8876 8.78633C10.5295 7.22834 9.26667 6.63336 8.20488 6.60269C7.14309 6.63949 5.88025 7.22834 5.52213 8.78633C5.43417 9.18503 5.34621 10.0683 4.44149 10.9516C4.00798 11.3748 1.86556 12.8408 2.88337 14.8282Z" fill="currentcolor"></path>
</svg>
                            </strong>
                                </span>
                            </h2>
                            <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" name="username" id="id_username" class="form-control" placeholder="Enter your username" required>
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email</label>
                                <input type="email" name="email" id="id_email" class="form-control" placeholder="Enter your email" required>
                            </div>
                            <div class="form-group">
                                <label for="id_phone">Phone Number</label>
                                <input type="text" name="phone" id="id_phone" class="form-control" placeholder="Enter your phone number" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password1">Password</label>
                                <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Enter your password" required>
                            </div>
                            <div class="form-group">
                                <label for="id_password2">Confirm Password</label>
                                <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Confirm your password" required>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary">Signup <img src="{% static 'assets/img/icon/right_arrow.svg' %}" alt="" class="injectable"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/user/login_req.html
{% extends "home/base.html" %}
{% load static %}
{% load products_tag %}
 {% block title %}You need to be logged in{% endblock title %}
{% block content %}
    <style>
        .login-required-container {
            text-align: center;
            margin-top: 50px;
            width: 100%;
            padding: 20px;  /* Optional padding for better spacing */
        }
        .login-required-container img {
            width: 80%;  /* Set your desired width */
            height: auto;  /* Maintain aspect ratio */
            max-width: 100%;  /* Responsive design */
        }
    </style>
<br>
<br>

    <div class="login-required-container container">
        <img src="{% static 'assets/img/login_first.png' %}" alt="Login Required" class="img-fluid">
        <div class="mt-3">
            <a class="btn" href="{% url 'login' %}">Login to continue</a>
        </div>
    </div>

        <div class="shape-two">
                            <img src="/static/assets/img/images/testimonial_shape03.png" alt="img" class="alltuchtopdown">
                            
                        </div>
                       
    <div class="team__shape">
        <img src="/static/assets/img/team/team_shape.png" alt="img" class="ribbonRotate">
        
    </div>
    <div class="testimonial__shape-wrap">
        <img src="/static/assets/img/images/testimonial_shape01.png" alt="img" data-aos="fade-down-right" data-aos-delay="400" class="aos-init aos-animate">
    </div>
    <div class="footer__shape-wrap">
                    <img src="/static/assets/img/images/footer_shape01.png" alt="img" data-aos="fade-up-right" data-aos-delay="400" class="aos-init aos-animate">
                    <img src="/static/assets/img/images/footer_shape02.png" alt="img" data-aos="fade-up-left" data-aos-delay="400" class="aos-init aos-animate">
                </div>

{%endblock content%}